# Generated by Django 4.2.1 on 2023-07-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='name1',
        ),
    ]
